plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '0.6.3'
}

group 'com.zj'
version '1.0'

repositories {
    maven { url 'http://maven.aliyun.com/nexus/content/groups/public/'}
    maven { url'https://maven.aliyun.com/repository/public/' }
    maven { url'https://maven.aliyun.com/repository/google/' }
    maven { url'https://maven.aliyun.com/repository/jcenter/' }
    maven { url'https://maven.aliyun.com/repository/central/' }
    google()
    jcenter()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation group: 'com.alibaba', name: 'fastjson', version: '2.0.39'
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.18'
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.18'
    implementation("org.apache.calcite:calcite-core:1.35.0") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    implementation("com.alibaba:easyexcel:3.3.3") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version '2020.1.2'
}
patchPluginXml {
    changeNotes """
      Add change notes here.<br>
      <em>most HTML tags may be used</em>"""
    // 前两位代表主版本的后两位【2020中20】， 最后一位是副版本 也就是2020.1
    sinceBuild = "201"
    // 最高支持版本
    untilBuild = '999.*'
}
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}


