plugins {
    id 'org.jetbrains.intellij' version '1.14.1'
}

group 'com.zj'
version '2022.2.5.6'

repositories {
    maven { url 'https://maven.aliyun.com/nexus/content/groups/public/'}
    maven { url'https://maven.aliyun.com/repository/public/' }
    maven { url'https://maven.aliyun.com/repository/google/' }
    maven { url'https://maven.aliyun.com/repository/jcenter/' }
    maven { url'https://maven.aliyun.com/repository/central/' }
    google()
}

dependencies {
    implementation project(':json-sql-core')
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    // jdk 升到17
    plugins = ['com.intellij.java']
    version = '2022.2.5'
}
patchPluginXml {
    //最低支持的版本
    //版本参考：https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html?from=jetbrains.org#intellij-platform-based-products-of-recent-ide-versions
    sinceBuild = '222'
    //最高支持的版本，不能不设置，不设置是默认为 project.version
    untilBuild = '222.*'
//    changeNotes = """
//      2024.3.4.1版本.<br>
//      修复了一些报错问题<br>
//      """
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
tasks.register("prepareKotlinBuildScriptModel"){}



