plugins {
    id 'org.jetbrains.intellij' version '1.0'
}

group 'com.zj'
version '2020.1.2.9'

repositories {
    maven { url 'https://maven.aliyun.com/nexus/content/groups/public/'}
    maven { url'https://maven.aliyun.com/repository/public/' }
    maven { url'https://maven.aliyun.com/repository/google/' }
    maven { url'https://maven.aliyun.com/repository/jcenter/' }
    maven { url'https://maven.aliyun.com/repository/central/' }
    google()
}

dependencies {
    implementation project(':json-sql-core')
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    // jdk 升到11
    plugins = ['com.intellij.java']
    version = '2020.1.2'
}
patchPluginXml {
    //最低支持的版本
    //版本参考：https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html?from=jetbrains.org#intellij-platform-based-products-of-recent-ide-versions
    sinceBuild = '201'
    //最高支持的版本，不能不设置，不设置是默认为 project.version
    untilBuild = '221.*'
    changeNotes = """
      Support excel export and import<br>
      Support having<br>
      Support +、-、*、/、% four fundamental rules<br>
      <br>
      <br>
      支持excel导入导出<br>
      支持having<br>
      支持+、-、*、/、% 四则运算<br>
      """
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
tasks.register("prepareKotlinBuildScriptModel"){}


tasks {
    buildPlugin {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    prepareSandbox {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    // mac指定为此idea运行环境，其他系统请参考： https://github.com/JetBrains/JetBrainsRuntime/releases
//    buildSearchableOptions {
//        jbrVersion = 'jbr_jcef-11_0_12b1649.1'
//    }
//    runIde {
//        jbrVersion = 'jbr_jcef-11_0_12b1649.1'
//    }
}

