plugins {
    id 'org.jetbrains.intellij' version '1.0'
}

group 'com.zj'
version '2020.1.2.1'

repositories {
    maven { url 'https://maven.aliyun.com/nexus/content/groups/public/'}
    maven { url'https://maven.aliyun.com/repository/public/' }
    maven { url'https://maven.aliyun.com/repository/google/' }
    maven { url'https://maven.aliyun.com/repository/jcenter/' }
    maven { url'https://maven.aliyun.com/repository/central/' }
    google()
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.13.1'
    implementation group: 'com.alibaba', name: 'fastjson', version: '2.0.39'
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.34'
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.34'
    implementation("org.apache.calcite:calcite-core:1.35.0") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
        exclude group: 'commons-io', module: 'commons-io'
        exclude group: 'org.apache.commons', module: 'commons-math3'
        exclude group: 'commons-codec', module: 'commons-codec'
    }
    implementation("com.alibaba:easyexcel:3.3.3") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    implementation project(':json-sql-core')
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    // jdk 升到11
    plugins = ['com.intellij.java']
    version = '2020.1.1'
}
patchPluginXml {
    //最低支持的版本
    //版本参考：https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html?from=jetbrains.org#intellij-platform-based-products-of-recent-ide-versions
    sinceBuild = '201'
    //最高支持的版本，不能不设置，不设置是默认为 project.version
    untilBuild = ''
//    changeNotes = """
//      2024.3.4.1版本.<br>
//      修复了一些报错问题<br>
//      """
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
tasks.register("prepareKotlinBuildScriptModel"){}


tasks {
    buildPlugin {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    prepareSandbox {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    // mac指定为此idea运行环境，其他系统请参考： https://github.com/JetBrains/JetBrainsRuntime/releases
//    buildSearchableOptions {
//        jbrVersion = 'jbr_jcef-11_0_12b1649.1'
//    }
//    runIde {
//        jbrVersion = 'jbr_jcef-11_0_12b1649.1'
//    }
}

